In [1]:
import pandas as pd
import os
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd().parent

file_path = BASE_DIR / "data" / "cleaned_data" / "cleaned_data.csv"

df = pd.read_csv(file_path, index_col=0)

In [3]:
df.head()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
2023-01-12,33.0,53.0,34.0,6566.0,436.0
2023-01-13,NaN,NaN,NaN,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN

In [4]:
df.rename(columns={"Children in CBP custody": "total load on CBP"}, inplace=True)

In [5]:
df.rename(columns={"Children in HHS Care": "total load on HHS"}, inplace=True)

In [6]:
# Balance between inflow and out-flow of children in CBP custody
df['CBP Custody net change'] = df['Children apprehended and placed in CBP custody*'] - df['Children transferred out of CBP custody']

In [7]:
df['CBP Custody net change']

2023-01-12   -1.0
2023-01-13    NaN
2023-01-14    NaN
2023-01-15    NaN
2023-01-16    NaN
             ...
2025-12-17   -4.0
2025-12-18    5.0
2025-12-19    NaN
2025-12-20    NaN
2025-12-21   -5.0
Name: CBP Custody net change, Length: 1075, dtype: float64

In [8]:
# Balance between inflow and out-flow of children in HHS care
df['HHS Net Flow'] = df['Children transferred out of CBP custody'] - df['Children discharged from HHS Care']

In [9]:
df['HHS Net Flow']

2023-01-12   -402.0
2023-01-13      NaN
2023-01-14      NaN
2023-01-15      NaN
2023-01-16      NaN
              ...
2025-12-17      1.0
2025-12-18    -10.0
2025-12-19      NaN
2025-12-20      NaN
2025-12-21     -3.0
Name: HHS Net Flow, Length: 1075, dtype: float64

In [10]:
df.head()

,Children apprehended and placed in CBP custody*,total load on CBP,Children transferred out of CBP custody,total load on HHS,Children discharged from HHS Care,CBP Custody net change,HHS Net Flow
2023-01-12,33.0,53.0,34.0,6566.0,436.0,-1.0,-402.0
2023-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
folder_path = r'C:\Users\as330\OneDrive\Desktop\UAC-Care-System\data\cleaned_data'
os.makedirs(folder_path, exist_ok=True)
df.to_csv(os.path.join(folder_path, 'sorted_data.csv'), index=True)