In [10]:
# Problem - 3
# ADDING STESS AND RELIEF PERIOD USING NET-FLOW OF CBP AND HHS AND THE DAILY INTAKE OF BOTH OF THEM
import pandas as pd
from pathlib import Path
import numpy as np

In [ ]:
BASE_DIR = Path.cwd().parent
file_path = BASE_DIR / "data" / "cleaned_data" / "sorted_data.csv"

df = pd.read_csv(file_path, index_col=0)

In [5]:
df.head()

,Children apprehended and placed in CBP custody*,total load on CBP,Children transferred out of CBP custody,total load on HHS,Children discharged from HHS Care,CBP Custody net change,HHS Net Flow
2023-01-12,33.0,53.0,34.0,6566.0,436.0,-1.0,-402.0
2023-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
avg_load_on_CBP = df['total load on CBP'].mean()
print(avg_load_on_CBP)

max_CBP_Custody_net_change = df['CBP Custody net change'].max()
print(max_CBP_Custody_net_change)

171.49444444444444
84.0

In [14]:
def classify(row):
    if ((row['total load on CBP'] > avg_load_on_CBP) & (row['CBP Custody net change'] > 20)):
        return "Stress"
    else:
        return "Relief"

df['daily status'] = df.apply(classify, axis=1)

In [18]:
values = df['daily status'] == "Stress"
print(values.sum())

27

In [21]:
df

,Children apprehended and placed in CBP custody*,total load on CBP,Children transferred out of CBP custody,total load on HHS,Children discharged from HHS Care,CBP Custody net change,HHS Net Flow,daily status
2023-01-12,33.0,53.0,34.0,6566.0,436.0,-1.0,-402.0,Relief
2023-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Relief
2023-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Relief
2023-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Relief
2023-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Relief
...,...,...,...,...,...,...,...,...
2025-12-17,7.0,31.0,11.0,2481.0,10.0,-4.0,1.0,Relief
2025-12-18,11.0,50.0,6.0,2472.0,16.0,5.0,-10.0,Relief
2025-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Relief
2025-12-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Relief
2025-12-21,6.0,18.0,11.0,2484.0,14.0,-5.0,-3.0,Relief